/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author USER
 */
public class ViewAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form ViewSistema
     */
    public ViewAdministrador() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnombrePer = new javax.swing.JTextField();
        txtapellidoPer = new javax.swing.JTextField();
        txtcedulaPer = new javax.swing.JTextField();
        txtcorreoPer = new javax.swing.JTextField();
        txtcelularPer = new javax.swing.JTextField();
        txtdireccionPer = new javax.swing.JTextField();
        btnguardarPer = new javax.swing.JButton();
        btneditarPer = new javax.swing.JButton();
        btneliminarPer = new javax.swing.JButton();
        btnlimpiarPer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtBsq = new javax.swing.JTextField();
        btnbuscarPer = new javax.swing.JButton();
        btnlimpiarPerbsq = new javax.swing.JButton();
        chekBsqPer = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jSeparator26 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPersonas = new javax.swing.JTable();
        jSeparator27 = new javax.swing.JSeparator();
        btnimprimirPer = new javax.swing.JButton();
        btnimprimirPer2 = new javax.swing.JButton();
        btncancelarPer = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtnombrePer1 = new javax.swing.JTextField();
        txtapellidoPer1 = new javax.swing.JTextField();
        txtcedulaPer1 = new javax.swing.JTextField();
        txtcorreoPer1 = new javax.swing.JTextField();
        txtcelularPer1 = new javax.swing.JTextField();
        txtdireccionPer1 = new javax.swing.JTextField();
        btnguardarPer1 = new javax.swing.JButton();
        btneditarPer1 = new javax.swing.JButton();
        btneliminarPer1 = new javax.swing.JButton();
        btnlimpiarPer1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator28 = new javax.swing.JSeparator();
        jSeparator29 = new javax.swing.JSeparator();
        jSeparator30 = new javax.swing.JSeparator();
        jSeparator31 = new javax.swing.JSeparator();
        jSeparator32 = new javax.swing.JSeparator();
        jSeparator33 = new javax.swing.JSeparator();
        jSeparator34 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator35 = new javax.swing.JSeparator();
        jSeparator36 = new javax.swing.JSeparator();
        jPanel11 = new javax.swing.JPanel();
        jSeparator37 = new javax.swing.JSeparator();
        jSeparator38 = new javax.swing.JSeparator();
        jSeparator39 = new javax.swing.JSeparator();
        jSeparator40 = new javax.swing.JSeparator();
        jSeparator41 = new javax.swing.JSeparator();
        jSeparator42 = new javax.swing.JSeparator();
        jSeparator43 = new javax.swing.JSeparator();
        jSeparator44 = new javax.swing.JSeparator();
        jSeparator45 = new javax.swing.JSeparator();
        jSeparator46 = new javax.swing.JSeparator();
        jSeparator47 = new javax.swing.JSeparator();
        jSeparator48 = new javax.swing.JSeparator();
        jSeparator49 = new javax.swing.JSeparator();
        jSeparator50 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtBsq1 = new javax.swing.JTextField();
        btnbuscarPer1 = new javax.swing.JButton();
        btnlimpiarPerbsq1 = new javax.swing.JButton();
        chekBsqPer1 = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jSeparator51 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPersonas1 = new javax.swing.JTable();
        jSeparator52 = new javax.swing.JSeparator();
        btnimprimirPer1 = new javax.swing.JButton();
        btnimprimirPer3 = new javax.swing.JButton();
        btncancelarPer1 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txtnombrePer2 = new javax.swing.JTextField();
        txtapellidoPer2 = new javax.swing.JTextField();
        txtcedulaPer2 = new javax.swing.JTextField();
        txtcorreoPer2 = new javax.swing.JTextField();
        txtcelularPer2 = new javax.swing.JTextField();
        txtdireccionPer2 = new javax.swing.JTextField();
        btnguardarPer2 = new javax.swing.JButton();
        btneditarPer2 = new javax.swing.JButton();
        btneliminarPer2 = new javax.swing.JButton();
        btnlimpiarPer2 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSeparator53 = new javax.swing.JSeparator();
        jSeparator54 = new javax.swing.JSeparator();
        jSeparator55 = new javax.swing.JSeparator();
        jSeparator56 = new javax.swing.JSeparator();
        jSeparator57 = new javax.swing.JSeparator();
        jSeparator58 = new javax.swing.JSeparator();
        jSeparator59 = new javax.swing.JSeparator();
        jSeparator60 = new javax.swing.JSeparator();
        jSeparator61 = new javax.swing.JSeparator();
        jSeparator62 = new javax.swing.JSeparator();
        jPanel14 = new javax.swing.JPanel();
        jSeparator63 = new javax.swing.JSeparator();
        jSeparator64 = new javax.swing.JSeparator();
        jSeparator65 = new javax.swing.JSeparator();
        jSeparator66 = new javax.swing.JSeparator();
        jSeparator67 = new javax.swing.JSeparator();
        jSeparator68 = new javax.swing.JSeparator();
        jSeparator69 = new javax.swing.JSeparator();
        jSeparator70 = new javax.swing.JSeparator();
        jSeparator71 = new javax.swing.JSeparator();
        jSeparator72 = new javax.swing.JSeparator();
        jSeparator73 = new javax.swing.JSeparator();
        jSeparator74 = new javax.swing.JSeparator();
        jSeparator75 = new javax.swing.JSeparator();
        jSeparator76 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtBsq2 = new javax.swing.JTextField();
        btnbuscarPer2 = new javax.swing.JButton();
        btnlimpiarPerbsq2 = new javax.swing.JButton();
        chekBsqPer2 = new javax.swing.JCheckBox();
        jLabel34 = new javax.swing.JLabel();
        jSeparator77 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPersonas2 = new javax.swing.JTable();
        jSeparator78 = new javax.swing.JSeparator();
        btnimprimirPer4 = new javax.swing.JButton();
        btnimprimirPer5 = new javax.swing.JButton();
        btncancelarPer2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(209, 200, 184));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users.png"))); // NOI18N
        jButton1.setText("USUARIOS");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 180, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empresario.png"))); // NOI18N
        jButton2.setText("JEFE ");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 180, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/assistant.png"))); // NOI18N
        jButton3.setText("ASISTENTE");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 180, 50));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        jButton4.setText("REPORTES");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 180, 50));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings.png"))); // NOI18N
        jButton5.setText("CONFIGURACIÓN");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 180, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 670));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reportes", jPanel2);

        jPanel6.setBackground(new java.awt.Color(249, 247, 250));

        jPanel7.setBackground(new java.awt.Color(249, 247, 250));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("  Administración de Usuarios");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 176, 20));

        txtnombrePer.setBackground(new java.awt.Color(249, 247, 250));
        txtnombrePer.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtnombrePer.setBorder(null);
        jPanel7.add(txtnombrePer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 290, -1));

        txtapellidoPer.setBackground(new java.awt.Color(249, 247, 250));
        txtapellidoPer.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtapellidoPer.setBorder(null);
        jPanel7.add(txtapellidoPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 290, -1));

        txtcedulaPer.setBackground(new java.awt.Color(249, 247, 250));
        txtcedulaPer.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtcedulaPer.setBorder(null);
        jPanel7.add(txtcedulaPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 290, -1));

        txtcorreoPer.setBackground(new java.awt.Color(249, 247, 250));
        txtcorreoPer.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtcorreoPer.setBorder(null);
        jPanel7.add(txtcorreoPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 290, -1));

        txtcelularPer.setBackground(new java.awt.Color(249, 247, 250));
        txtcelularPer.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtcelularPer.setBorder(null);
        jPanel7.add(txtcelularPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 290, -1));

        txtdireccionPer.setBackground(new java.awt.Color(249, 247, 250));
        txtdireccionPer.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtdireccionPer.setBorder(null);
        jPanel7.add(txtdireccionPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 290, -1));

        btnguardarPer.setBackground(new java.awt.Color(249, 247, 250));
        btnguardarPer.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnguardarPer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(btnguardarPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 40, 30));

        btneditarPer.setBackground(new java.awt.Color(249, 247, 250));
        btneditarPer.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btneditarPer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(btneditarPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 40, 30));

        btneliminarPer.setBackground(new java.awt.Color(249, 247, 250));
        btneliminarPer.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btneliminarPer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(btneliminarPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 40, 30));

        btnlimpiarPer.setBackground(new java.awt.Color(249, 247, 250));
        btnlimpiarPer.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnlimpiarPer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(btnlimpiarPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 40, 30));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Nombres");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Apellidos");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Cédula");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Correo");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Celular");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Dirección");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 290, -1));

        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 290, -1));

        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 290, -1));

        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 290, -1));

        jSeparator10.setForeground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 290, 10));

        jSeparator11.setForeground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 290, 10));

        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 160, 10));

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel7.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 10, 390));

        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 330, 10));

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel7.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 380));

        jPanel8.setBackground(new java.awt.Color(249, 247, 250));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator12.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 19, 220, 13));

        jSeparator13.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 30, 390));

        jSeparator14.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 590, 10));

        jSeparator15.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 220, 10));

        jSeparator16.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 420, 10));

        jSeparator17.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator17.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 40, 70));

        jSeparator18.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 10, 10));

        jSeparator19.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 570, 10));

        jSeparator20.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 10, 10));

        jSeparator21.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 450, 10));

        jSeparator22.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator22.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 20, 260));

        jSeparator23.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator23.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 10, 70));

        jSeparator24.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 250, 10));

        jSeparator25.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator25.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 10, 390));

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel9.setText("Búsqueda de Usuarios");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel10.setText(" Opciones de Búsqueda");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 20));

        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Criterio");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 50, 20));

        txtBsq.setBackground(new java.awt.Color(249, 247, 250));
        txtBsq.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtBsq.setBorder(null);
        jPanel8.add(txtBsq, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 250, -1));

        btnbuscarPer.setBackground(new java.awt.Color(249, 247, 250));
        btnbuscarPer.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        btnbuscarPer.setText("Buscar");
        btnbuscarPer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(btnbuscarPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 80, 30));

        btnlimpiarPerbsq.setBackground(new java.awt.Color(249, 247, 250));
        btnlimpiarPerbsq.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnlimpiarPerbsq.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(btnlimpiarPerbsq, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 40, 30));

        chekBsqPer.setBackground(new java.awt.Color(249, 247, 250));
        chekBsqPer.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        chekBsqPer.setText("Mostrar Todos");
        chekBsqPer.setBorder(null);
        jPanel8.add(chekBsqPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 110, 30));

        jLabel12.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel12.setText(" Lista de Usuarios");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 20));

        jSeparator26.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 570, 10));

        tblPersonas.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        tblPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblPersonas);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 550, 180));

        jSeparator27.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator27.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 10, 260));

        btnimprimirPer.setBackground(new java.awt.Color(249, 247, 250));
        btnimprimirPer.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnimprimirPer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(btnimprimirPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 40, 30));

        btnimprimirPer2.setBackground(new java.awt.Color(249, 247, 250));
        btnimprimirPer2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnimprimirPer2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(btnimprimirPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 40, 30));

        btncancelarPer.setBackground(new java.awt.Color(249, 247, 250));
        btncancelarPer.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        btncancelarPer.setText("Cancelar");
        btncancelarPer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(btncancelarPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 80, 30));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Usuarios", jPanel6);

        jPanel9.setBackground(new java.awt.Color(249, 247, 250));

        jPanel10.setBackground(new java.awt.Color(249, 247, 250));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("  Administración de Jefes");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 176, 20));

        txtnombrePer1.setBackground(new java.awt.Color(249, 247, 250));
        txtnombrePer1.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtnombrePer1.setBorder(null);
        jPanel10.add(txtnombrePer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 290, -1));

        txtapellidoPer1.setBackground(new java.awt.Color(249, 247, 250));
        txtapellidoPer1.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtapellidoPer1.setBorder(null);
        jPanel10.add(txtapellidoPer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 290, -1));

        txtcedulaPer1.setBackground(new java.awt.Color(249, 247, 250));
        txtcedulaPer1.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtcedulaPer1.setBorder(null);
        jPanel10.add(txtcedulaPer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 290, -1));

        txtcorreoPer1.setBackground(new java.awt.Color(249, 247, 250));
        txtcorreoPer1.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtcorreoPer1.setBorder(null);
        jPanel10.add(txtcorreoPer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 290, -1));

        txtcelularPer1.setBackground(new java.awt.Color(249, 247, 250));
        txtcelularPer1.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtcelularPer1.setBorder(null);
        jPanel10.add(txtcelularPer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 290, -1));

        txtdireccionPer1.setBackground(new java.awt.Color(249, 247, 250));
        txtdireccionPer1.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtdireccionPer1.setBorder(null);
        jPanel10.add(txtdireccionPer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 290, -1));

        btnguardarPer1.setBackground(new java.awt.Color(249, 247, 250));
        btnguardarPer1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnguardarPer1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.add(btnguardarPer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 40, 30));

        btneditarPer1.setBackground(new java.awt.Color(249, 247, 250));
        btneditarPer1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btneditarPer1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.add(btneditarPer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 40, 30));

        btneliminarPer1.setBackground(new java.awt.Color(249, 247, 250));
        btneliminarPer1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btneliminarPer1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.add(btneliminarPer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 40, 30));

        btnlimpiarPer1.setBackground(new java.awt.Color(249, 247, 250));
        btnlimpiarPer1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnlimpiarPer1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.add(btnlimpiarPer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 40, 30));

        jLabel14.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Nombres");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel15.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Apellidos");
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel16.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Cédula");
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel17.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Correo");
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel18.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Celular");
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel19.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Dirección");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jSeparator28.setForeground(new java.awt.Color(204, 204, 204));
        jPanel10.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 290, -1));

        jSeparator29.setForeground(new java.awt.Color(204, 204, 204));
        jPanel10.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 290, -1));

        jSeparator30.setForeground(new java.awt.Color(204, 204, 204));
        jPanel10.add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 290, -1));

        jSeparator31.setForeground(new java.awt.Color(204, 204, 204));
        jPanel10.add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 290, -1));

        jSeparator32.setForeground(new java.awt.Color(204, 204, 204));
        jPanel10.add(jSeparator32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 290, 10));

        jSeparator33.setForeground(new java.awt.Color(204, 204, 204));
        jPanel10.add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 290, 10));

        jSeparator34.setForeground(new java.awt.Color(204, 204, 204));
        jPanel10.add(jSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 160, 10));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel10.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 10, 390));

        jSeparator35.setForeground(new java.awt.Color(204, 204, 204));
        jPanel10.add(jSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 330, 10));

        jSeparator36.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator36.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel10.add(jSeparator36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 380));

        jPanel11.setBackground(new java.awt.Color(249, 247, 250));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator37.setForeground(new java.awt.Color(204, 204, 204));
        jPanel11.add(jSeparator37, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 19, 220, 13));

        jSeparator38.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator38.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel11.add(jSeparator38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 30, 390));

        jSeparator39.setForeground(new java.awt.Color(204, 204, 204));
        jPanel11.add(jSeparator39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 590, 10));

        jSeparator40.setForeground(new java.awt.Color(204, 204, 204));
        jPanel11.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 220, 10));

        jSeparator41.setForeground(new java.awt.Color(204, 204, 204));
        jPanel11.add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 420, 10));

        jSeparator42.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator42.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel11.add(jSeparator42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 40, 70));

        jSeparator43.setForeground(new java.awt.Color(204, 204, 204));
        jPanel11.add(jSeparator43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 10, 10));

        jSeparator44.setForeground(new java.awt.Color(204, 204, 204));
        jPanel11.add(jSeparator44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 570, 10));

        jSeparator45.setForeground(new java.awt.Color(204, 204, 204));
        jPanel11.add(jSeparator45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 10, 10));

        jSeparator46.setForeground(new java.awt.Color(204, 204, 204));
        jPanel11.add(jSeparator46, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 450, 10));

        jSeparator47.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator47.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel11.add(jSeparator47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 20, 260));

        jSeparator48.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator48.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel11.add(jSeparator48, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 10, 70));

        jSeparator49.setForeground(new java.awt.Color(204, 204, 204));
        jPanel11.add(jSeparator49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 250, 10));

        jSeparator50.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator50.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel11.add(jSeparator50, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 10, 390));

        jLabel20.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel20.setText("Búsqueda de Jefes");
        jPanel11.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel21.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel21.setText(" Opciones de Búsqueda");
        jPanel11.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 20));

        jLabel22.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Criterio");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 50, 20));

        txtBsq1.setBackground(new java.awt.Color(249, 247, 250));
        txtBsq1.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtBsq1.setBorder(null);
        jPanel11.add(txtBsq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 250, -1));

        btnbuscarPer1.setBackground(new java.awt.Color(249, 247, 250));
        btnbuscarPer1.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        btnbuscarPer1.setText("Buscar");
        btnbuscarPer1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.add(btnbuscarPer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 80, 30));

        btnlimpiarPerbsq1.setBackground(new java.awt.Color(249, 247, 250));
        btnlimpiarPerbsq1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnlimpiarPerbsq1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.add(btnlimpiarPerbsq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 40, 30));

        chekBsqPer1.setBackground(new java.awt.Color(249, 247, 250));
        chekBsqPer1.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        chekBsqPer1.setText("Mostrar Todos");
        chekBsqPer1.setBorder(null);
        jPanel11.add(chekBsqPer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 110, 30));

        jLabel23.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel23.setText(" Lista de Jefes");
        jPanel11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        jSeparator51.setForeground(new java.awt.Color(204, 204, 204));
        jPanel11.add(jSeparator51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 570, 10));

        tblPersonas1.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        tblPersonas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tblPersonas1);

        jPanel11.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 550, 180));

        jSeparator52.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator52.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel11.add(jSeparator52, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 10, 260));

        btnimprimirPer1.setBackground(new java.awt.Color(249, 247, 250));
        btnimprimirPer1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnimprimirPer1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.add(btnimprimirPer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 40, 30));

        btnimprimirPer3.setBackground(new java.awt.Color(249, 247, 250));
        btnimprimirPer3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnimprimirPer3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.add(btnimprimirPer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 40, 30));

        btncancelarPer1.setBackground(new java.awt.Color(249, 247, 250));
        btncancelarPer1.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        btncancelarPer1.setText("Cancelar");
        btncancelarPer1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.add(btncancelarPer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 80, 30));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Jefes", jPanel9);

        jPanel12.setBackground(new java.awt.Color(249, 247, 250));

        jPanel13.setBackground(new java.awt.Color(249, 247, 250));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("  Administración de Asistentes");
        jPanel13.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 176, 20));

        txtnombrePer2.setBackground(new java.awt.Color(249, 247, 250));
        txtnombrePer2.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtnombrePer2.setBorder(null);
        jPanel13.add(txtnombrePer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 290, -1));

        txtapellidoPer2.setBackground(new java.awt.Color(249, 247, 250));
        txtapellidoPer2.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtapellidoPer2.setBorder(null);
        jPanel13.add(txtapellidoPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 290, -1));

        txtcedulaPer2.setBackground(new java.awt.Color(249, 247, 250));
        txtcedulaPer2.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtcedulaPer2.setBorder(null);
        jPanel13.add(txtcedulaPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 290, -1));

        txtcorreoPer2.setBackground(new java.awt.Color(249, 247, 250));
        txtcorreoPer2.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtcorreoPer2.setBorder(null);
        jPanel13.add(txtcorreoPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 290, -1));

        txtcelularPer2.setBackground(new java.awt.Color(249, 247, 250));
        txtcelularPer2.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtcelularPer2.setBorder(null);
        jPanel13.add(txtcelularPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 290, -1));

        txtdireccionPer2.setBackground(new java.awt.Color(249, 247, 250));
        txtdireccionPer2.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtdireccionPer2.setBorder(null);
        jPanel13.add(txtdireccionPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 290, -1));

        btnguardarPer2.setBackground(new java.awt.Color(249, 247, 250));
        btnguardarPer2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnguardarPer2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.add(btnguardarPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 40, 30));

        btneditarPer2.setBackground(new java.awt.Color(249, 247, 250));
        btneditarPer2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btneditarPer2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.add(btneditarPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 40, 30));

        btneliminarPer2.setBackground(new java.awt.Color(249, 247, 250));
        btneliminarPer2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btneliminarPer2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.add(btneliminarPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 40, 30));

        btnlimpiarPer2.setBackground(new java.awt.Color(249, 247, 250));
        btnlimpiarPer2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnlimpiarPer2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.add(btnlimpiarPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 40, 30));

        jLabel25.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Nombres");
        jPanel13.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel26.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Apellidos");
        jPanel13.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel27.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Cédula");
        jPanel13.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel28.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Correo");
        jPanel13.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel29.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Celular");
        jPanel13.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel30.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Dirección");
        jPanel13.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jSeparator53.setForeground(new java.awt.Color(204, 204, 204));
        jPanel13.add(jSeparator53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 290, -1));

        jSeparator54.setForeground(new java.awt.Color(204, 204, 204));
        jPanel13.add(jSeparator54, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 290, -1));

        jSeparator55.setForeground(new java.awt.Color(204, 204, 204));
        jPanel13.add(jSeparator55, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 290, -1));

        jSeparator56.setForeground(new java.awt.Color(204, 204, 204));
        jPanel13.add(jSeparator56, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 290, -1));

        jSeparator57.setForeground(new java.awt.Color(204, 204, 204));
        jPanel13.add(jSeparator57, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 290, 10));

        jSeparator58.setForeground(new java.awt.Color(204, 204, 204));
        jPanel13.add(jSeparator58, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 290, 10));

        jSeparator59.setForeground(new java.awt.Color(204, 204, 204));
        jPanel13.add(jSeparator59, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 160, 10));

        jSeparator60.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator60.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel13.add(jSeparator60, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 10, 390));

        jSeparator61.setForeground(new java.awt.Color(204, 204, 204));
        jPanel13.add(jSeparator61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 330, 10));

        jSeparator62.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator62.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel13.add(jSeparator62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 380));

        jPanel14.setBackground(new java.awt.Color(249, 247, 250));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator63.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.add(jSeparator63, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 19, 220, 13));

        jSeparator64.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator64.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel14.add(jSeparator64, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 30, 390));

        jSeparator65.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.add(jSeparator65, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 590, 10));

        jSeparator66.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.add(jSeparator66, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 220, 10));

        jSeparator67.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.add(jSeparator67, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 420, 10));

        jSeparator68.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator68.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel14.add(jSeparator68, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 40, 70));

        jSeparator69.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.add(jSeparator69, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 10, 10));

        jSeparator70.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.add(jSeparator70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 570, 10));

        jSeparator71.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.add(jSeparator71, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 10, 10));

        jSeparator72.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.add(jSeparator72, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 450, 10));

        jSeparator73.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator73.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel14.add(jSeparator73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 20, 260));

        jSeparator74.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator74.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel14.add(jSeparator74, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 10, 70));

        jSeparator75.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.add(jSeparator75, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 250, 10));

        jSeparator76.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator76.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel14.add(jSeparator76, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 10, 390));

        jLabel31.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel31.setText("Búsqueda de Asistentes");
        jPanel14.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel32.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel32.setText(" Opciones de Búsqueda");
        jPanel14.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 20));

        jLabel33.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("Criterio");
        jPanel14.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 50, 20));

        txtBsq2.setBackground(new java.awt.Color(249, 247, 250));
        txtBsq2.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtBsq2.setBorder(null);
        jPanel14.add(txtBsq2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 250, -1));

        btnbuscarPer2.setBackground(new java.awt.Color(249, 247, 250));
        btnbuscarPer2.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        btnbuscarPer2.setText("Buscar");
        btnbuscarPer2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.add(btnbuscarPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 80, 30));

        btnlimpiarPerbsq2.setBackground(new java.awt.Color(249, 247, 250));
        btnlimpiarPerbsq2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnlimpiarPerbsq2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.add(btnlimpiarPerbsq2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 40, 30));

        chekBsqPer2.setBackground(new java.awt.Color(249, 247, 250));
        chekBsqPer2.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        chekBsqPer2.setText("Mostrar Todos");
        chekBsqPer2.setBorder(null);
        jPanel14.add(chekBsqPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 110, 30));

        jLabel34.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel34.setText(" Lista de Asistentes");
        jPanel14.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        jSeparator77.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.add(jSeparator77, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 570, 10));

        tblPersonas2.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        tblPersonas2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(tblPersonas2);

        jPanel14.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 550, 180));

        jSeparator78.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator78.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel14.add(jSeparator78, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 10, 260));

        btnimprimirPer4.setBackground(new java.awt.Color(249, 247, 250));
        btnimprimirPer4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnimprimirPer4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.add(btnimprimirPer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 40, 30));

        btnimprimirPer5.setBackground(new java.awt.Color(249, 247, 250));
        btnimprimirPer5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnimprimirPer5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.add(btnimprimirPer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 40, 30));

        btncancelarPer2.setBackground(new java.awt.Color(249, 247, 250));
        btncancelarPer2.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        btncancelarPer2.setText("Cancelar");
        btncancelarPer2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.add(btncancelarPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 80, 30));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Asistentes", jPanel12);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 960, 500));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Encabezado.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 960, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscarPer;
    private javax.swing.JButton btnbuscarPer1;
    private javax.swing.JButton btnbuscarPer2;
    private javax.swing.JButton btncancelarPer;
    private javax.swing.JButton btncancelarPer1;
    private javax.swing.JButton btncancelarPer2;
    private javax.swing.JButton btneditarPer;
    private javax.swing.JButton btneditarPer1;
    private javax.swing.JButton btneditarPer2;
    private javax.swing.JButton btneliminarPer;
    private javax.swing.JButton btneliminarPer1;
    private javax.swing.JButton btneliminarPer2;
    private javax.swing.JButton btnguardarPer;
    private javax.swing.JButton btnguardarPer1;
    private javax.swing.JButton btnguardarPer2;
    private javax.swing.JButton btnimprimirPer;
    private javax.swing.JButton btnimprimirPer1;
    private javax.swing.JButton btnimprimirPer2;
    private javax.swing.JButton btnimprimirPer3;
    private javax.swing.JButton btnimprimirPer4;
    private javax.swing.JButton btnimprimirPer5;
    private javax.swing.JButton btnlimpiarPer;
    private javax.swing.JButton btnlimpiarPer1;
    private javax.swing.JButton btnlimpiarPer2;
    private javax.swing.JButton btnlimpiarPerbsq;
    private javax.swing.JButton btnlimpiarPerbsq1;
    private javax.swing.JButton btnlimpiarPerbsq2;
    private javax.swing.JCheckBox chekBsqPer;
    private javax.swing.JCheckBox chekBsqPer1;
    private javax.swing.JCheckBox chekBsqPer2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator43;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator45;
    private javax.swing.JSeparator jSeparator46;
    private javax.swing.JSeparator jSeparator47;
    private javax.swing.JSeparator jSeparator48;
    private javax.swing.JSeparator jSeparator49;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator50;
    private javax.swing.JSeparator jSeparator51;
    private javax.swing.JSeparator jSeparator52;
    private javax.swing.JSeparator jSeparator53;
    private javax.swing.JSeparator jSeparator54;
    private javax.swing.JSeparator jSeparator55;
    private javax.swing.JSeparator jSeparator56;
    private javax.swing.JSeparator jSeparator57;
    private javax.swing.JSeparator jSeparator58;
    private javax.swing.JSeparator jSeparator59;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator60;
    private javax.swing.JSeparator jSeparator61;
    private javax.swing.JSeparator jSeparator62;
    private javax.swing.JSeparator jSeparator63;
    private javax.swing.JSeparator jSeparator64;
    private javax.swing.JSeparator jSeparator65;
    private javax.swing.JSeparator jSeparator66;
    private javax.swing.JSeparator jSeparator67;
    private javax.swing.JSeparator jSeparator68;
    private javax.swing.JSeparator jSeparator69;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator70;
    private javax.swing.JSeparator jSeparator71;
    private javax.swing.JSeparator jSeparator72;
    private javax.swing.JSeparator jSeparator73;
    private javax.swing.JSeparator jSeparator74;
    private javax.swing.JSeparator jSeparator75;
    private javax.swing.JSeparator jSeparator76;
    private javax.swing.JSeparator jSeparator77;
    private javax.swing.JSeparator jSeparator78;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblPersonas;
    private javax.swing.JTable tblPersonas1;
    private javax.swing.JTable tblPersonas2;
    private javax.swing.JTextField txtBsq;
    private javax.swing.JTextField txtBsq1;
    private javax.swing.JTextField txtBsq2;
    private javax.swing.JTextField txtapellidoPer;
    private javax.swing.JTextField txtapellidoPer1;
    private javax.swing.JTextField txtapellidoPer2;
    private javax.swing.JTextField txtcedulaPer;
    private javax.swing.JTextField txtcedulaPer1;
    private javax.swing.JTextField txtcedulaPer2;
    private javax.swing.JTextField txtcelularPer;
    private javax.swing.JTextField txtcelularPer1;
    private javax.swing.JTextField txtcelularPer2;
    private javax.swing.JTextField txtcorreoPer;
    private javax.swing.JTextField txtcorreoPer1;
    private javax.swing.JTextField txtcorreoPer2;
    private javax.swing.JTextField txtdireccionPer;
    private javax.swing.JTextField txtdireccionPer1;
    private javax.swing.JTextField txtdireccionPer2;
    private javax.swing.JTextField txtnombrePer;
    private javax.swing.JTextField txtnombrePer1;
    private javax.swing.JTextField txtnombrePer2;
    // End of variables declaration//GEN-END:variables
}
