/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author USER
 */
public class ViewAsistente extends javax.swing.JFrame {

    /**
     * Creates new form ViewSistema
     */
    public ViewAsistente() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        pnPrincipal = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnPersona = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtnombrePer4 = new javax.swing.JTextField();
        txtapellidoPer4 = new javax.swing.JTextField();
        txtcedulaPer4 = new javax.swing.JTextField();
        txtcorreoPer4 = new javax.swing.JTextField();
        txtcelularPer4 = new javax.swing.JTextField();
        txtdireccionPer4 = new javax.swing.JTextField();
        btnguardarPer4 = new javax.swing.JButton();
        btneditarPer4 = new javax.swing.JButton();
        btneliminarPer4 = new javax.swing.JButton();
        btnlimpiarPer4 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jSeparator37 = new javax.swing.JSeparator();
        jSeparator38 = new javax.swing.JSeparator();
        jSeparator39 = new javax.swing.JSeparator();
        jSeparator40 = new javax.swing.JSeparator();
        jSeparator41 = new javax.swing.JSeparator();
        jSeparator42 = new javax.swing.JSeparator();
        jLabel50 = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        rbtFemenino = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        rbtMasculino = new javax.swing.JRadioButton();
        jLabel51 = new javax.swing.JLabel();
        txtnombrePer5 = new javax.swing.JTextField();
        jSeparator43 = new javax.swing.JSeparator();
        jLabel52 = new javax.swing.JLabel();
        txtnombrePer6 = new javax.swing.JTextField();
        jSeparator44 = new javax.swing.JSeparator();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        txtnombrePer7 = new javax.swing.JTextField();
        jSeparator45 = new javax.swing.JSeparator();
        jSeparator46 = new javax.swing.JSeparator();
        jLabel55 = new javax.swing.JLabel();
        txtnombrePer8 = new javax.swing.JTextField();
        jSeparator48 = new javax.swing.JSeparator();
        jSeparator49 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel56 = new javax.swing.JLabel();
        txtnombrePer9 = new javax.swing.JTextField();
        jSeparator50 = new javax.swing.JSeparator();
        jLabel57 = new javax.swing.JLabel();
        txtnombrePer10 = new javax.swing.JTextField();
        jSeparator51 = new javax.swing.JSeparator();
        jLabel58 = new javax.swing.JLabel();
        txtnombrePer11 = new javax.swing.JTextField();
        jSeparator80 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        btnExaminarFoto = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        btnlimpiarPerbsq4 = new javax.swing.JButton();
        btnbuscarPer4 = new javax.swing.JButton();
        chekBsqPer4 = new javax.swing.JCheckBox();
        jLabel40 = new javax.swing.JLabel();
        txtBsq4 = new javax.swing.JTextField();
        pn = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        btnguardarPer = new javax.swing.JButton();
        btneditarPer = new javax.swing.JButton();
        btneliminarPer = new javax.swing.JButton();
        btnlimpiarPer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        jSeparator79 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtBsq = new javax.swing.JTextField();
        btnbuscarPer = new javax.swing.JButton();
        btnlimpiarPerbsq = new javax.swing.JButton();
        chekBsqPer = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jSeparator26 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPersonas = new javax.swing.JTable();
        jSeparator27 = new javax.swing.JSeparator();
        btnimprimirPer = new javax.swing.JButton();
        btnimprimirPer2 = new javax.swing.JButton();
        btncancelarPer = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txtnombrePer2 = new javax.swing.JTextField();
        txtapellidoPer2 = new javax.swing.JTextField();
        txtcedulaPer2 = new javax.swing.JTextField();
        txtcorreoPer2 = new javax.swing.JTextField();
        txtcelularPer2 = new javax.swing.JTextField();
        txtdireccionPer2 = new javax.swing.JTextField();
        btnguardarPer2 = new javax.swing.JButton();
        btneditarPer2 = new javax.swing.JButton();
        btneliminarPer2 = new javax.swing.JButton();
        btnlimpiarPer2 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSeparator53 = new javax.swing.JSeparator();
        jSeparator54 = new javax.swing.JSeparator();
        jSeparator55 = new javax.swing.JSeparator();
        jSeparator56 = new javax.swing.JSeparator();
        jSeparator57 = new javax.swing.JSeparator();
        jSeparator58 = new javax.swing.JSeparator();
        jSeparator59 = new javax.swing.JSeparator();
        jSeparator60 = new javax.swing.JSeparator();
        jSeparator61 = new javax.swing.JSeparator();
        jSeparator62 = new javax.swing.JSeparator();
        jPanel14 = new javax.swing.JPanel();
        jSeparator63 = new javax.swing.JSeparator();
        jSeparator64 = new javax.swing.JSeparator();
        jSeparator65 = new javax.swing.JSeparator();
        jSeparator66 = new javax.swing.JSeparator();
        jSeparator67 = new javax.swing.JSeparator();
        jSeparator68 = new javax.swing.JSeparator();
        jSeparator69 = new javax.swing.JSeparator();
        jSeparator70 = new javax.swing.JSeparator();
        jSeparator71 = new javax.swing.JSeparator();
        jSeparator72 = new javax.swing.JSeparator();
        jSeparator73 = new javax.swing.JSeparator();
        jSeparator74 = new javax.swing.JSeparator();
        jSeparator75 = new javax.swing.JSeparator();
        jSeparator76 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtBsq2 = new javax.swing.JTextField();
        btnbuscarPer2 = new javax.swing.JButton();
        btnlimpiarPerbsq2 = new javax.swing.JButton();
        chekBsqPer2 = new javax.swing.JCheckBox();
        jLabel34 = new javax.swing.JLabel();
        jSeparator77 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPersonas2 = new javax.swing.JTable();
        jSeparator78 = new javax.swing.JSeparator();
        btnimprimirPer4 = new javax.swing.JButton();
        btnimprimirPer5 = new javax.swing.JButton();
        btncancelarPer2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(209, 200, 184));
        jPanel3.setLayout(new java.awt.BorderLayout());

        pnPrincipal.setBackground(new java.awt.Color(30, 28, 64));
        pnPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(43, 45, 66));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings.png"))); // NOI18N
        jButton5.setText("SALIR");
        pnPrincipal.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 180, -1));

        pnPersona.setBackground(new java.awt.Color(249, 247, 250));
        pnPersona.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrar Personas ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnombrePer4.setBackground(new java.awt.Color(249, 247, 250));
        txtnombrePer4.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtnombrePer4.setBorder(null);
        jPanel5.add(txtnombrePer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 33, 200, -1));

        txtapellidoPer4.setBackground(new java.awt.Color(249, 247, 250));
        txtapellidoPer4.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtapellidoPer4.setBorder(null);
        jPanel5.add(txtapellidoPer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 153, 200, -1));

        txtcedulaPer4.setBackground(new java.awt.Color(249, 247, 250));
        txtcedulaPer4.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtcedulaPer4.setBorder(null);
        jPanel5.add(txtcedulaPer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 204, 200, -1));

        txtcorreoPer4.setBackground(new java.awt.Color(249, 247, 250));
        txtcorreoPer4.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtcorreoPer4.setBorder(null);
        jPanel5.add(txtcorreoPer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 324, 200, -1));

        txtcelularPer4.setBackground(new java.awt.Color(249, 247, 250));
        txtcelularPer4.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtcelularPer4.setBorder(null);
        jPanel5.add(txtcelularPer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 149, 200, 20));

        txtdireccionPer4.setBackground(new java.awt.Color(249, 247, 250));
        txtdireccionPer4.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtdireccionPer4.setBorder(null);
        jPanel5.add(txtdireccionPer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 383, 207, -1));

        btnguardarPer4.setBackground(new java.awt.Color(249, 247, 250));
        btnguardarPer4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnguardarPer4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(btnguardarPer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 781, 40, 30));

        btneditarPer4.setBackground(new java.awt.Color(249, 247, 250));
        btneditarPer4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btneditarPer4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(btneditarPer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 781, 40, 30));

        btneliminarPer4.setBackground(new java.awt.Color(249, 247, 250));
        btneliminarPer4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btneliminarPer4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(btneliminarPer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 767, 40, 30));

        btnlimpiarPer4.setBackground(new java.awt.Color(249, 247, 250));
        btnlimpiarPer4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnlimpiarPer4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(btnlimpiarPer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 781, 40, 30));

        jLabel44.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(102, 102, 102));
        jLabel44.setText("Identificación");
        jPanel5.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 18, -1, -1));

        jLabel45.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(102, 102, 102));
        jLabel45.setText("Nombres:");
        jPanel5.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 135, -1, -1));

        jLabel46.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(102, 102, 102));
        jLabel46.setText("Apellidos:");
        jPanel5.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 184, -1, -1));

        jLabel47.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(102, 102, 102));
        jLabel47.setText("Dirección:");
        jPanel5.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 304, -1, -1));

        jLabel48.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(102, 102, 102));
        jLabel48.setText("Teléfono:");
        jPanel5.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 129, -1, -1));

        jLabel49.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(102, 102, 102));
        jLabel49.setText("Correo:");
        jPanel5.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 363, -1, -1));

        jSeparator37.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator37, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 54, 200, 14));

        jSeparator38.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator38, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 174, 200, 2));

        jSeparator39.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator39, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 224, 200, 4));

        jSeparator40.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 345, 200, 12));

        jSeparator41.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 412, 207, 10));

        jSeparator42.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator42, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 175, 200, 10));

        jLabel50.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(102, 102, 102));
        jLabel50.setText("Tipo:");
        jPanel5.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 74, -1, -1));

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(cbxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 91, 200, 20));

        rbtFemenino.setText("Femenino");
        rbtFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtFemeninoActionPerformed(evt);
            }
        });
        jPanel5.add(rbtFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 38, -1, -1));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Género:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 18, -1, -1));

        rbtMasculino.setText("Masculino");
        jPanel5.add(rbtMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 38, -1, -1));

        jLabel51.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(102, 102, 102));
        jLabel51.setText("Estado Civil:");
        jPanel5.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 274, -1, -1));

        txtnombrePer5.setBackground(new java.awt.Color(249, 247, 250));
        txtnombrePer5.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtnombrePer5.setBorder(null);
        jPanel5.add(txtnombrePer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 294, 180, -1));

        jSeparator43.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator43, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 118, 200, 11));

        jLabel52.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(102, 102, 102));
        jLabel52.setText("Estrato Social:");
        jPanel5.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 428, -1, -1));

        txtnombrePer6.setBackground(new java.awt.Color(249, 247, 250));
        txtnombrePer6.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtnombrePer6.setBorder(null);
        jPanel5.add(txtnombrePer6, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 448, 200, -1));

        jSeparator44.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator44, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 468, 200, 13));

        jLabel53.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(102, 102, 102));
        jLabel53.setText("Fecha de Nacimiento:");
        jPanel5.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 246, 112, -1));

        jLabel54.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(102, 102, 102));
        jLabel54.setText("Salario:");
        jPanel5.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 345, -1, -1));

        txtnombrePer7.setBackground(new java.awt.Color(249, 247, 250));
        txtnombrePer7.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtnombrePer7.setBorder(null);
        jPanel5.add(txtnombrePer7, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 371, 180, -1));

        jSeparator45.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator45, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 392, 180, 11));

        jSeparator46.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator46, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 315, 180, 12));

        jLabel55.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(102, 102, 102));
        jLabel55.setText("Título:");
        jPanel5.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 304, -1, -1));

        txtnombrePer8.setBackground(new java.awt.Color(249, 247, 250));
        txtnombrePer8.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtnombrePer8.setBorder(null);
        jPanel5.add(txtnombrePer8, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 324, 200, -1));

        jSeparator48.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator48, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 345, 200, 12));

        jSeparator49.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator49, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 117, 200, 12));

        jCheckBox1.setText("Seguro IEES");
        jPanel5.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 91, 200, -1));

        jLabel56.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(102, 102, 102));
        jLabel56.setText("Horario:");
        jPanel5.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 363, -1, -1));

        txtnombrePer9.setBackground(new java.awt.Color(249, 247, 250));
        txtnombrePer9.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtnombrePer9.setBorder(null);
        jPanel5.add(txtnombrePer9, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 383, 200, -1));

        jSeparator50.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator50, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 405, 200, 14));

        jLabel57.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(102, 102, 102));
        jLabel57.setText("Periodo:");
        jPanel5.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 425, -1, -1));

        txtnombrePer10.setBackground(new java.awt.Color(249, 247, 250));
        txtnombrePer10.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtnombrePer10.setBorder(null);
        jPanel5.add(txtnombrePer10, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 445, 200, -1));

        jSeparator51.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator51, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 466, 200, 24));

        jLabel58.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(102, 102, 102));
        jLabel58.setText("Tipo de Voluntario:");
        jPanel5.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 425, -1, -1));

        txtnombrePer11.setBackground(new java.awt.Color(249, 247, 250));
        txtnombrePer11.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtnombrePer11.setBorder(null);
        jPanel5.add(txtnombrePer11, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 445, 180, -1));

        jSeparator80.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator80, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 466, 180, 15));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 21, -1, -1));

        btnExaminarFoto.setText("Examinar");
        jPanel5.add(btnExaminarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 207, 147, 21));
        jPanel5.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 276, 200, -1));

        pnPersona.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 580));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda Persona", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel15.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        pnPersona.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 470, 470));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda Persona", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel16.setForeground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlimpiarPerbsq4.setBackground(new java.awt.Color(249, 247, 250));
        btnlimpiarPerbsq4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnlimpiarPerbsq4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel16.add(btnlimpiarPerbsq4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 40, 30));

        btnbuscarPer4.setBackground(new java.awt.Color(249, 247, 250));
        btnbuscarPer4.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        btnbuscarPer4.setText("Buscar");
        btnbuscarPer4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel16.add(btnbuscarPer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 80, 30));

        chekBsqPer4.setBackground(new java.awt.Color(249, 247, 250));
        chekBsqPer4.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        chekBsqPer4.setText("Mostrar Todos");
        chekBsqPer4.setBorder(null);
        jPanel16.add(chekBsqPer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 90, 30));

        jLabel40.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(102, 102, 102));
        jLabel40.setText("Criterio");
        jPanel16.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 50, 20));

        txtBsq4.setBackground(new java.awt.Color(249, 247, 250));
        txtBsq4.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtBsq4.setBorder(null);
        jPanel16.add(txtBsq4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, -1));

        pnPersona.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 470, 110));

        jTabbedPane1.addTab("Benefactor", pnPersona);

        pn.setBackground(new java.awt.Color(249, 247, 250));

        jPanel7.setBackground(new java.awt.Color(249, 247, 250));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("  Administración de Personas");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 176, 20));

        txtcedula.setBackground(new java.awt.Color(249, 247, 250));
        txtcedula.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtcedula.setBorder(null);
        jPanel7.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 290, -1));

        txtcorreo.setBackground(new java.awt.Color(249, 247, 250));
        txtcorreo.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtcorreo.setBorder(null);
        jPanel7.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 290, -1));

        txtnombre.setBackground(new java.awt.Color(249, 247, 250));
        txtnombre.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtnombre.setBorder(null);
        jPanel7.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 290, -1));

        txtapellido.setBackground(new java.awt.Color(249, 247, 250));
        txtapellido.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtapellido.setBorder(null);
        jPanel7.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 290, -1));

        txtdireccion.setBackground(new java.awt.Color(249, 247, 250));
        txtdireccion.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtdireccion.setBorder(null);
        jPanel7.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 290, -1));

        txttelefono.setBackground(new java.awt.Color(249, 247, 250));
        txttelefono.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txttelefono.setBorder(null);
        jPanel7.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 290, -1));

        btnguardarPer.setBackground(new java.awt.Color(249, 247, 250));
        btnguardarPer.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnguardarPer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(btnguardarPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 40, 30));

        btneditarPer.setBackground(new java.awt.Color(249, 247, 250));
        btneditarPer.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btneditarPer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(btneditarPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 40, 30));

        btneliminarPer.setBackground(new java.awt.Color(249, 247, 250));
        btneliminarPer.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btneliminarPer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(btneliminarPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 40, 30));

        btnlimpiarPer.setBackground(new java.awt.Color(249, 247, 250));
        btnlimpiarPer.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnlimpiarPer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(btnlimpiarPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 40, 30));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Identificación:");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Tipo:");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Nombres:");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Apellidos:");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Dirección:");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 290, -1));

        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 290, -1));

        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 290, -1));

        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 290, -1));

        jSeparator10.setForeground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 290, 10));

        jSeparator11.setForeground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 290, 10));

        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 160, 10));

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel7.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 10, 390));

        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 330, 10));

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel7.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 10, 380));

        jLabel35.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("Teléfono:");
        jPanel7.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jSeparator79.setForeground(new java.awt.Color(204, 204, 204));
        jPanel7.add(jSeparator79, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 290, 10));

        jLabel36.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("Correo:");
        jPanel7.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jPanel8.setBackground(new java.awt.Color(249, 247, 250));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator12.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 19, 220, 13));

        jSeparator13.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 30, 390));

        jSeparator14.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 590, 10));

        jSeparator15.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 220, 10));

        jSeparator16.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 420, 10));

        jSeparator17.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator17.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 40, 70));

        jSeparator18.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 10, 10));

        jSeparator19.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 570, 10));

        jSeparator20.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 10, 10));

        jSeparator21.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 450, 10));

        jSeparator22.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator22.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 20, 260));

        jSeparator23.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator23.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 10, 70));

        jSeparator24.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 250, 10));

        jSeparator25.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator25.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 10, 390));

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel9.setText("Búsqueda de Usuarios");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel10.setText(" Opciones de Búsqueda");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 20));

        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Criterio");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 50, 20));

        txtBsq.setBackground(new java.awt.Color(249, 247, 250));
        txtBsq.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtBsq.setBorder(null);
        jPanel8.add(txtBsq, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 250, -1));

        btnbuscarPer.setBackground(new java.awt.Color(249, 247, 250));
        btnbuscarPer.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        btnbuscarPer.setText("Buscar");
        btnbuscarPer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(btnbuscarPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 80, 30));

        btnlimpiarPerbsq.setBackground(new java.awt.Color(249, 247, 250));
        btnlimpiarPerbsq.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnlimpiarPerbsq.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(btnlimpiarPerbsq, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 40, 30));

        chekBsqPer.setBackground(new java.awt.Color(249, 247, 250));
        chekBsqPer.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        chekBsqPer.setText("Mostrar Todos");
        chekBsqPer.setBorder(null);
        jPanel8.add(chekBsqPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 110, 30));

        jLabel12.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel12.setText(" Lista de Usuarios");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 20));

        jSeparator26.setForeground(new java.awt.Color(204, 204, 204));
        jPanel8.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 570, 10));

        tblPersonas.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        tblPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblPersonas);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 550, 180));

        jSeparator27.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator27.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 10, 260));

        btnimprimirPer.setBackground(new java.awt.Color(249, 247, 250));
        btnimprimirPer.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnimprimirPer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(btnimprimirPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 40, 30));

        btnimprimirPer2.setBackground(new java.awt.Color(249, 247, 250));
        btnimprimirPer2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnimprimirPer2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(btnimprimirPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 40, 30));

        btncancelarPer.setBackground(new java.awt.Color(249, 247, 250));
        btncancelarPer.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        btncancelarPer.setText("Cancelar");
        btncancelarPer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(btncancelarPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 80, 30));

        javax.swing.GroupLayout pnLayout = new javax.swing.GroupLayout(pn);
        pn.setLayout(pnLayout);
        pnLayout.setHorizontalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnLayout.setVerticalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Beneficiario", pn);

        jPanel12.setBackground(new java.awt.Color(249, 247, 250));

        jPanel13.setBackground(new java.awt.Color(249, 247, 250));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("  Administración de Asistentes");
        jPanel13.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 176, 20));

        txtnombrePer2.setBackground(new java.awt.Color(249, 247, 250));
        txtnombrePer2.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtnombrePer2.setBorder(null);
        jPanel13.add(txtnombrePer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 290, -1));

        txtapellidoPer2.setBackground(new java.awt.Color(249, 247, 250));
        txtapellidoPer2.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtapellidoPer2.setBorder(null);
        jPanel13.add(txtapellidoPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 290, -1));

        txtcedulaPer2.setBackground(new java.awt.Color(249, 247, 250));
        txtcedulaPer2.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtcedulaPer2.setBorder(null);
        jPanel13.add(txtcedulaPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 290, -1));

        txtcorreoPer2.setBackground(new java.awt.Color(249, 247, 250));
        txtcorreoPer2.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtcorreoPer2.setBorder(null);
        jPanel13.add(txtcorreoPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 290, -1));

        txtcelularPer2.setBackground(new java.awt.Color(249, 247, 250));
        txtcelularPer2.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtcelularPer2.setBorder(null);
        jPanel13.add(txtcelularPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 290, -1));

        txtdireccionPer2.setBackground(new java.awt.Color(249, 247, 250));
        txtdireccionPer2.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtdireccionPer2.setBorder(null);
        jPanel13.add(txtdireccionPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 290, -1));

        btnguardarPer2.setBackground(new java.awt.Color(249, 247, 250));
        btnguardarPer2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnguardarPer2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.add(btnguardarPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 40, 30));

        btneditarPer2.setBackground(new java.awt.Color(249, 247, 250));
        btneditarPer2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btneditarPer2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.add(btneditarPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 40, 30));

        btneliminarPer2.setBackground(new java.awt.Color(249, 247, 250));
        btneliminarPer2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btneliminarPer2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.add(btneliminarPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 40, 30));

        btnlimpiarPer2.setBackground(new java.awt.Color(249, 247, 250));
        btnlimpiarPer2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnlimpiarPer2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.add(btnlimpiarPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 40, 30));

        jLabel25.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Nombres");
        jPanel13.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel26.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Apellidos");
        jPanel13.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel27.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Cédula");
        jPanel13.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel28.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Correo");
        jPanel13.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel29.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Celular");
        jPanel13.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel30.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Dirección");
        jPanel13.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jSeparator53.setForeground(new java.awt.Color(204, 204, 204));
        jPanel13.add(jSeparator53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 290, -1));

        jSeparator54.setForeground(new java.awt.Color(204, 204, 204));
        jPanel13.add(jSeparator54, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 290, -1));

        jSeparator55.setForeground(new java.awt.Color(204, 204, 204));
        jPanel13.add(jSeparator55, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 290, -1));

        jSeparator56.setForeground(new java.awt.Color(204, 204, 204));
        jPanel13.add(jSeparator56, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 290, -1));

        jSeparator57.setForeground(new java.awt.Color(204, 204, 204));
        jPanel13.add(jSeparator57, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 290, 10));

        jSeparator58.setForeground(new java.awt.Color(204, 204, 204));
        jPanel13.add(jSeparator58, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 290, 10));

        jSeparator59.setForeground(new java.awt.Color(204, 204, 204));
        jPanel13.add(jSeparator59, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 160, 10));

        jSeparator60.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator60.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel13.add(jSeparator60, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 10, 390));

        jSeparator61.setForeground(new java.awt.Color(204, 204, 204));
        jPanel13.add(jSeparator61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 330, 10));

        jSeparator62.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator62.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel13.add(jSeparator62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 380));

        jPanel14.setBackground(new java.awt.Color(249, 247, 250));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator63.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.add(jSeparator63, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 19, 220, 13));

        jSeparator64.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator64.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel14.add(jSeparator64, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 30, 390));

        jSeparator65.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.add(jSeparator65, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 590, 10));

        jSeparator66.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.add(jSeparator66, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 220, 10));

        jSeparator67.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.add(jSeparator67, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 420, 10));

        jSeparator68.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator68.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel14.add(jSeparator68, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 40, 70));

        jSeparator69.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.add(jSeparator69, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 10, 10));

        jSeparator70.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.add(jSeparator70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 570, 10));

        jSeparator71.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.add(jSeparator71, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 10, 10));

        jSeparator72.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.add(jSeparator72, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 450, 10));

        jSeparator73.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator73.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel14.add(jSeparator73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 20, 260));

        jSeparator74.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator74.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel14.add(jSeparator74, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 10, 70));

        jSeparator75.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.add(jSeparator75, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 250, 10));

        jSeparator76.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator76.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel14.add(jSeparator76, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 10, 390));

        jLabel31.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel31.setText("Búsqueda de Asistentes");
        jPanel14.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel32.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel32.setText(" Opciones de Búsqueda");
        jPanel14.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 20));

        jLabel33.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("Criterio");
        jPanel14.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 50, 20));

        txtBsq2.setBackground(new java.awt.Color(249, 247, 250));
        txtBsq2.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        txtBsq2.setBorder(null);
        jPanel14.add(txtBsq2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 250, -1));

        btnbuscarPer2.setBackground(new java.awt.Color(249, 247, 250));
        btnbuscarPer2.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        btnbuscarPer2.setText("Buscar");
        btnbuscarPer2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.add(btnbuscarPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 80, 30));

        btnlimpiarPerbsq2.setBackground(new java.awt.Color(249, 247, 250));
        btnlimpiarPerbsq2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnlimpiarPerbsq2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.add(btnlimpiarPerbsq2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 40, 30));

        chekBsqPer2.setBackground(new java.awt.Color(249, 247, 250));
        chekBsqPer2.setFont(new java.awt.Font("Leelawadee UI", 1, 10)); // NOI18N
        chekBsqPer2.setText("Mostrar Todos");
        chekBsqPer2.setBorder(null);
        jPanel14.add(chekBsqPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 110, 30));

        jLabel34.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        jLabel34.setText(" Lista de Asistentes");
        jPanel14.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        jSeparator77.setForeground(new java.awt.Color(204, 204, 204));
        jPanel14.add(jSeparator77, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 570, 10));

        tblPersonas2.setFont(new java.awt.Font("Leelawadee UI", 0, 11)); // NOI18N
        tblPersonas2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(tblPersonas2);

        jPanel14.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 550, 180));

        jSeparator78.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator78.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel14.add(jSeparator78, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 10, 260));

        btnimprimirPer4.setBackground(new java.awt.Color(249, 247, 250));
        btnimprimirPer4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnimprimirPer4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.add(btnimprimirPer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 40, 30));

        btnimprimirPer5.setBackground(new java.awt.Color(249, 247, 250));
        btnimprimirPer5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnimprimirPer5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.add(btnimprimirPer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 40, 30));

        btncancelarPer2.setBackground(new java.awt.Color(249, 247, 250));
        btncancelarPer2.setFont(new java.awt.Font("Leelawadee UI", 1, 11)); // NOI18N
        btncancelarPer2.setText("Cancelar");
        btncancelarPer2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.add(btncancelarPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 80, 30));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Formulario", jPanel12);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(442, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reportes", jPanel2);

        pnPrincipal.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jLabel2.setBackground(new java.awt.Color(209, 200, 184));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enca1.png"))); // NOI18N
        jLabel2.setToolTipText("");
        pnPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1370, -1));

        jButton6.setBackground(new java.awt.Color(43, 45, 66));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-allotment-64.png"))); // NOI18N
        jButton6.setText("BENEFACTOR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        pnPrincipal.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 180, -1));

        jButton7.setBackground(new java.awt.Color(43, 45, 66));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-beneficiary-64 (1).png"))); // NOI18N
        jButton7.setText("BENEFICIARIO");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        pnPrincipal.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 180, -1));

        jButton8.setBackground(new java.awt.Color(43, 45, 66));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-form-64.png"))); // NOI18N
        jButton8.setText("FORMULARIO");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        pnPrincipal.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 180, -1));

        jPanel3.add(pnPrincipal, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtFemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtFemeninoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        System.out.println("sad");
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAsistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAsistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAsistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAsistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAsistente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExaminarFoto;
    private javax.swing.JButton btnbuscarPer;
    private javax.swing.JButton btnbuscarPer2;
    private javax.swing.JButton btnbuscarPer4;
    private javax.swing.JButton btncancelarPer;
    private javax.swing.JButton btncancelarPer2;
    private javax.swing.JButton btneditarPer;
    private javax.swing.JButton btneditarPer2;
    private javax.swing.JButton btneditarPer4;
    private javax.swing.JButton btneliminarPer;
    private javax.swing.JButton btneliminarPer2;
    private javax.swing.JButton btneliminarPer4;
    private javax.swing.JButton btnguardarPer;
    private javax.swing.JButton btnguardarPer2;
    private javax.swing.JButton btnguardarPer4;
    private javax.swing.JButton btnimprimirPer;
    private javax.swing.JButton btnimprimirPer2;
    private javax.swing.JButton btnimprimirPer4;
    private javax.swing.JButton btnimprimirPer5;
    private javax.swing.JButton btnlimpiarPer;
    private javax.swing.JButton btnlimpiarPer2;
    private javax.swing.JButton btnlimpiarPer4;
    private javax.swing.JButton btnlimpiarPerbsq;
    private javax.swing.JButton btnlimpiarPerbsq2;
    private javax.swing.JButton btnlimpiarPerbsq4;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JCheckBox chekBsqPer;
    private javax.swing.JCheckBox chekBsqPer2;
    private javax.swing.JCheckBox chekBsqPer4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator43;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator45;
    private javax.swing.JSeparator jSeparator46;
    private javax.swing.JSeparator jSeparator48;
    private javax.swing.JSeparator jSeparator49;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator50;
    private javax.swing.JSeparator jSeparator51;
    private javax.swing.JSeparator jSeparator53;
    private javax.swing.JSeparator jSeparator54;
    private javax.swing.JSeparator jSeparator55;
    private javax.swing.JSeparator jSeparator56;
    private javax.swing.JSeparator jSeparator57;
    private javax.swing.JSeparator jSeparator58;
    private javax.swing.JSeparator jSeparator59;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator60;
    private javax.swing.JSeparator jSeparator61;
    private javax.swing.JSeparator jSeparator62;
    private javax.swing.JSeparator jSeparator63;
    private javax.swing.JSeparator jSeparator64;
    private javax.swing.JSeparator jSeparator65;
    private javax.swing.JSeparator jSeparator66;
    private javax.swing.JSeparator jSeparator67;
    private javax.swing.JSeparator jSeparator68;
    private javax.swing.JSeparator jSeparator69;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator70;
    private javax.swing.JSeparator jSeparator71;
    private javax.swing.JSeparator jSeparator72;
    private javax.swing.JSeparator jSeparator73;
    private javax.swing.JSeparator jSeparator74;
    private javax.swing.JSeparator jSeparator75;
    private javax.swing.JSeparator jSeparator76;
    private javax.swing.JSeparator jSeparator77;
    private javax.swing.JSeparator jSeparator78;
    private javax.swing.JSeparator jSeparator79;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator80;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JPanel pn;
    private javax.swing.JPanel pnPersona;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JRadioButton rbtFemenino;
    private javax.swing.JRadioButton rbtMasculino;
    private javax.swing.JTable tblPersonas;
    private javax.swing.JTable tblPersonas2;
    private javax.swing.JTextField txtBsq;
    private javax.swing.JTextField txtBsq2;
    private javax.swing.JTextField txtBsq4;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtapellidoPer2;
    private javax.swing.JTextField txtapellidoPer4;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcedulaPer2;
    private javax.swing.JTextField txtcedulaPer4;
    private javax.swing.JTextField txtcelularPer2;
    private javax.swing.JTextField txtcelularPer4;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtcorreoPer2;
    private javax.swing.JTextField txtcorreoPer4;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdireccionPer2;
    private javax.swing.JTextField txtdireccionPer4;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnombrePer10;
    private javax.swing.JTextField txtnombrePer11;
    private javax.swing.JTextField txtnombrePer2;
    private javax.swing.JTextField txtnombrePer4;
    private javax.swing.JTextField txtnombrePer5;
    private javax.swing.JTextField txtnombrePer6;
    private javax.swing.JTextField txtnombrePer7;
    private javax.swing.JTextField txtnombrePer8;
    private javax.swing.JTextField txtnombrePer9;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
